# brings up Go server + Next.js in dev
services:
  db: 
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}


  # to git inside docker DB: 
  # docker exec -it db psql -U postgres

  # to git inside docker DB: 
  # docker ps -a

